In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from rl.rl_auxilliary import QNet, SVODataset, SVODatasetFromLog


In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

In [33]:
model_path = '/home/nbuckman/mpc-multiple-vehicles/rl/runs/0225_1631nbuckman-desktop/model.pt'

In [34]:
q_network = torch.load(model_path)
q_network.to(device)

QNet(
  (fc_input): Linear(in_features=5, out_features=25, bias=True)
  (dropout_input): Dropout(p=0.1, inplace=False)
  (input_layer): Sequential(
    (0): Linear(in_features=5, out_features=25, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.1, inplace=False)
  )
  (dropout_hidden): Dropout(p=0.25, inplace=False)
  (fc_hidden): Linear(in_features=25, out_features=25, bias=True)
  (relu_hidden): ReLU()
  (hidden_layer): Sequential(
    (0): Linear(in_features=25, out_features=25, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.25, inplace=False)
  )
  (model): Sequential(
    (0): Sequential(
      (0): Sequential(
        (0): Sequential(
          (0): Linear(in_features=5, out_features=25, bias=True)
          (1): ReLU()
          (2): Dropout(p=0.1, inplace=False)
        )
        (1): Sequential(
          (0): Linear(in_features=25, out_features=25, bias=True)
          (1): ReLU()
          (2): Dropout(p=0.25, inplace=False)
        )
      )
      (1): Sequential(
        (

In [44]:
q_network.eval()
params = {
    "n_other": 4,
    "max_svo": np.pi/2.0,
    "learning_rate": 1e-6
}

INPUT_OPTIMIZER_EPOCHS = int(4000)
svo_inputs = torch.rand(1, params["n_other"] + 1, dtype=torch.double, device=device) * params["max_svo"]
svo_inputs.requires_grad_(True)
input_optimizer = optim.Adam([svo_inputs], params["learning_rate"])
for iop_epoch in range(INPUT_OPTIMIZER_EPOCHS):
    input_optimizer.zero_grad()
    output = q_network(svo_inputs.clamp(min=0, max=np.pi / 2))
    loss_to_min = output.sum()
#     writer.add_scalar("team_v_loss_min_%d" % ep_tix, loss_to_min, iop_epoch)
    loss_to_min.backward()
    input_optimizer.step()
    print(svo_inputs)

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)
tensor([[0.6912, 0.5466, 0.1219, 0.2133, 1.2984]], device='cuda:0',
    

KeyboardInterrupt: 

In [ ]:
svo_input = 10*svo_input

In [ ]:
import datetime

In [ ]:
datetime.datetime.now().strftime('%m%d_%H%M')

In [ ]:
import socket
print(socket.gethostname())

In [ ]:
int(1e5)

In [ ]:
svo_input

In [ ]:
svo